### ISSUE TITLE
landing page needs to be styled.

### ISSUE THREAD

**Issue by jsnoble** [EJJ-Brainstorm/Brainstorm#30]

**Comment by ekeric13** [comment]
should sort of look like this: https://www.airbnb.com/
nice background image of a whiteboard with a bunch of stickies from brainstorming with some large big white text in front of it.
http://b.fastcompany.net/multisite_files/fastcompany/poster/2014/04/3028861-poster-p-1-3028861the-managers-one-minute-guide-to-brainstorming-apps.jpg
the big white text should be like "GET READY TO HAVE SOME FUN"
and the small text below should be like "and brainstorm more effectively than ever before"
